version: '3'
services:
  app:
    container_name: app  
    build: ./docker/php
    volumes:
      - .:/var/www
    working_dir: /var/www/src
  nginx:
    image: nginx:1.20.2 
    container_name: nginx
    ports:
      - 30001:80 
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/src
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: weight-app
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: zaq12wsx
      MYSQL_USER: user
      MYSQL_PASSWORD: zaq12wsx
      TZ: 'Asia/Tokyo' 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmy-admin  
    restart: always
    ports:
      - "30002:80"
    depends_on: 
      - db
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "30003:8025"
    volumes:
      - "./docker/mhsendmail:/usr/local/bin/mhsendmail"